In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

In [9]:
X,y=make_classification(n_samples=2000,n_features=10,n_classes=2,random_state=42)

In [10]:
X

array([[-0.89535437, -1.13342102,  2.33782775, ..., -0.8607568 ,
         0.34992372, -2.19197798],
       [ 0.54752653,  1.70754889,  1.43995404, ...,  1.07562679,
         0.91670647,  1.28316565],
       [ 1.63995668,  0.01048798,  0.53362642, ..., -1.45456141,
        -1.40005654,  0.05842084],
       ...,
       [ 0.30812834, -0.66168987,  0.54286372, ..., -0.02740229,
        -1.14057849,  1.19366944],
       [ 0.21630541,  0.8601508 ,  0.74627759, ...,  0.90079117,
        -0.65863208,  1.64632723],
       [ 1.1218615 , -2.07448635,  0.72906365, ...,  0.35116547,
        -0.02203486, -0.76661652]], shape=(2000, 10))

In [11]:
y

array([0, 1, 0, ..., 1, 1, 0], shape=(2000,))

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [13]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [15]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [18]:
y_pred=logistic.predict(X_test)
print(y_pred)

[0 1 1 0 1 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 1 0 1
 0 0 1 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 0 0
 0 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1
 0 1 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 1 1 1 0
 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 0 1 0 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 1 0
 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 1 1 0 1
 0 0 0 0 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 1 1 0
 1 0 1 0 0 0 1 0 1 1 1 0 1 0 1 1 0 1 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 1
 0 1 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 1 1 0 0 1
 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 1
 0 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 1
 1 1 0 1 1 1 0 1 0 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0
 1 1 1 1 1 0 0 1 1 0 1 1 

In [ ]:
logistic.predict_proba(X_test) #gives the prob of the output to be of that clas 8.2 means that much for it to be considered ) 
#1.79 for it to be 1 which evers highest is considered

array([[8.20207760e-01, 1.79792240e-01],
       [6.71478226e-02, 9.32852177e-01],
       [1.31639300e-03, 9.98683607e-01],
       [9.95480052e-01, 4.51994836e-03],
       [7.70912468e-02, 9.22908753e-01],
       [8.38699375e-02, 9.16130062e-01],
       [8.63449068e-01, 1.36550932e-01],
       [7.43713896e-01, 2.56286104e-01],
       [1.64492852e-01, 8.35507148e-01],
       [1.78152217e-01, 8.21847783e-01],
       [4.45878162e-02, 9.55412184e-01],
       [9.95864148e-01, 4.13585225e-03],
       [8.96876282e-02, 9.10312372e-01],
       [7.89875889e-01, 2.10124111e-01],
       [1.48267430e-02, 9.85173257e-01],
       [9.97606410e-01, 2.39359004e-03],
       [9.93653071e-01, 6.34692870e-03],
       [1.30383460e-01, 8.69616540e-01],
       [3.53910499e-01, 6.46089501e-01],
       [9.96820299e-01, 3.17970131e-03],
       [9.64583896e-01, 3.54161041e-02],
       [1.95000777e-01, 8.04999223e-01],
       [9.43651800e-01, 5.63481995e-02],
       [9.83172560e-01, 1.68274405e-02],
       [7.044087

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [26]:
score=accuracy_score(y_test,y_pred)
conf_matrix=confusion_matrix(y_test,y_pred)
report=classification_report(y_test,y_pred)
print(score)
print(conf_matrix)
print(report)

0.894
[[239  25]
 [ 28 208]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       264
           1       0.89      0.88      0.89       236

    accuracy                           0.89       500
   macro avg       0.89      0.89      0.89       500
weighted avg       0.89      0.89      0.89       500

